
# Storage Configuration
# Choose ONE storage backend by setting the connection string
storage_connection_string = "postgres://postgres:postgres@localhost:5432/sensapp"

# Alternative storage backends (uncomment one to use):
# storage_connection_string = "sqlite://sensapp.db"
# storage_connection_string = "duckdb://sensapp.db"
# storage_connection_string = "bigquery://key.json?project_id=PROJECT&dataset_id=DATASET"
# storage_connection_string = "rrdcached://localhost:42217?preset=munin"

# Network Configuration
#endpoint = "0.0.0.0"

# Optional Configuration
# Sentry DSN for error tracking (leave commented to disable)
# sentry_dsn = "https://your-dsn@your-sentry-instance/project-id"

# Storage sync timeout in seconds (default: 15)
# storage_sync_timeout_seconds = 30

# InfluxDB Configuration
# Use Numeric/Decimal (high precision) for InfluxDB numeric values instead of Float (default: false)
# Numeric (Decimal) is precise but slower; Float (f64) is faster but has limited precision
# influxdb_with_numeric = false
