[config]
instance_id = 42
batch_size = 100
http_server_timeout_seconds = 30
http_body_limit = "64MB"

# Test database - use a test-specific database
storage_connection_string = "postgres://postgres:postgres@localhost:5432/sensapp_integration_test"

# HTTP server settings for tests
endpoint = [127, 0, 0, 1]
port = 8081

# No MQTT for tests
[[mqtt]]