
sqlite_connection_string = "sqlite:test.db"
#postgres_connection_string = "postgres://localhost:5432/postgres"
postgres_connection_string = "postgres://postgres:postgres@localhost:5432/postgres"
timescaledb_connection_string = "postgres://postgres:postgres@localhost:5432/sensapp"

#endpoint = "0.0.0.0"

