// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { frontpage, getSeriesData, listMetrics, listSeries, liveness, type Options, prometheusMetrics, prometheusRemoteRead, publishInfluxdb, publishPrometheus, publishSensorsData, readiness, simplePromqlQuery, vacuumDatabase } from '../sdk.gen';
import type { FrontpageData, FrontpageResponse, GetSeriesDataData, ListMetricsData, ListSeriesData, LivenessData, LivenessResponse, PrometheusMetricsData, PrometheusMetricsResponse, PrometheusRemoteReadData, PrometheusRemoteReadError, PublishInfluxdbData, PublishInfluxdbError, PublishInfluxdbResponse, PublishPrometheusData, PublishPrometheusError, PublishPrometheusResponse, PublishSensorsDataData, PublishSensorsDataError, PublishSensorsDataResponse, ReadinessData, ReadinessError, ReadinessResponse2, SimplePromqlQueryData, VacuumDatabaseData, VacuumDatabaseError, VacuumDatabaseResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const frontpageQueryKey = (options?: Options<FrontpageData>) => createQueryKey('frontpage', options);

export const frontpageOptions = (options?: Options<FrontpageData>) => queryOptions<FrontpageResponse, DefaultError, FrontpageResponse, ReturnType<typeof frontpageQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await frontpage({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: frontpageQueryKey(options)
});

/**
 * Database Vacuuming
 *
 * Cleans up and optimizes the database by removing unused data and reclaiming space.
 * (only if supported by the underlying storage engine).
 */
export const vacuumDatabaseMutation = (options?: Partial<Options<VacuumDatabaseData>>): UseMutationOptions<VacuumDatabaseResponse, VacuumDatabaseError, Options<VacuumDatabaseData>> => {
    const mutationOptions: UseMutationOptions<VacuumDatabaseResponse, VacuumDatabaseError, Options<VacuumDatabaseData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await vacuumDatabase({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Prometheus Remote Read API.
 *
 * Allows you to read data from SensApp using Prometheus remote read protocol.
 *
 * It follows the [Prometheus Remote Read specification](https://prometheus.io/docs/prometheus/latest/querying/remote_read_api/).
 */
export const prometheusRemoteReadMutation = (options?: Partial<Options<PrometheusRemoteReadData>>): UseMutationOptions<unknown, PrometheusRemoteReadError, Options<PrometheusRemoteReadData>> => {
    const mutationOptions: UseMutationOptions<unknown, PrometheusRemoteReadError, Options<PrometheusRemoteReadData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await prometheusRemoteRead({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Prometheus Remote Write API.
 *
 * Allows you to write data from Prometheus to SensApp.
 *
 * It follows the [Prometheus Remote Write specification](https://prometheus.io/docs/concepts/remote_write_spec/).
 */
export const publishPrometheusMutation = (options?: Partial<Options<PublishPrometheusData>>): UseMutationOptions<PublishPrometheusResponse, PublishPrometheusError, Options<PublishPrometheusData>> => {
    const mutationOptions: UseMutationOptions<PublishPrometheusResponse, PublishPrometheusError, Options<PublishPrometheusData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await publishPrometheus({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const simplePromqlQueryQueryKey = (options: Options<SimplePromqlQueryData>) => createQueryKey('simplePromqlQuery', options);

/**
 * Simple PromQL query endpoint.
 *
 * Parses a PromQL expression and returns matching time series data.
 * Only simple selectors (VectorSelector and MatrixSelector) are supported.
 *
 * # Examples
 *
 * - Simple metric: `GET /api/v1/query?query=my_metric`
 * - With labels: `GET /api/v1/query?query=my_metric{env="prod"}`
 * - Range query: `GET /api/v1/query?query=my_metric[5m]`
 * - With format: `GET /api/v1/query?query=my_metric&format=csv`
 */
export const simplePromqlQueryOptions = (options: Options<SimplePromqlQueryData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof simplePromqlQueryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await simplePromqlQuery({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: simplePromqlQueryQueryKey(options)
});

/**
 * InfluxDB Compatible Write API.
 *
 * Allows you to write data from InfluxDB or Telegraf to SensApp.
 * [More information.](https://github.com/SINTEF/sensapp/blob/main/docs/INFLUX_DB.md)
 */
export const publishInfluxdbMutation = (options?: Partial<Options<PublishInfluxdbData>>): UseMutationOptions<PublishInfluxdbResponse, PublishInfluxdbError, Options<PublishInfluxdbData>> => {
    const mutationOptions: UseMutationOptions<PublishInfluxdbResponse, PublishInfluxdbError, Options<PublishInfluxdbData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await publishInfluxdb({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const livenessQueryKey = (options?: Options<LivenessData>) => createQueryKey('liveness', options);

/**
 * Liveness check
 *
 * Checks if the service is running.
 * This endpoint always returns 200 OK if the server is able to respond.
 */
export const livenessOptions = (options?: Options<LivenessData>) => queryOptions<LivenessResponse, DefaultError, LivenessResponse, ReturnType<typeof livenessQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await liveness({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: livenessQueryKey(options)
});

export const readinessQueryKey = (options?: Options<ReadinessData>) => createQueryKey('readiness', options);

/**
 * Readiness check
 *
 * Checks if the service is ready to accept traffic.
 * This includes checking if the database connection is working
 */
export const readinessOptions = (options?: Options<ReadinessData>) => queryOptions<ReadinessResponse2, ReadinessError, ReadinessResponse2, ReturnType<typeof readinessQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readiness({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readinessQueryKey(options)
});

export const listMetricsQueryKey = (options?: Options<ListMetricsData>) => createQueryKey('listMetrics', options);

/**
 * List unique metrics (measurement types) with aggregated information in DCAT catalog format.
 */
export const listMetricsOptions = (options?: Options<ListMetricsData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof listMetricsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listMetrics({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listMetricsQueryKey(options)
});

export const prometheusMetricsQueryKey = (options?: Options<PrometheusMetricsData>) => createQueryKey('prometheusMetrics', options);

export const prometheusMetricsOptions = (options?: Options<PrometheusMetricsData>) => queryOptions<PrometheusMetricsResponse, DefaultError, PrometheusMetricsResponse, ReturnType<typeof prometheusMetricsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await prometheusMetrics({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: prometheusMetricsQueryKey(options)
});

/**
 * SensApp native data ingestion API supporting multiple formats.
 *
 * Accepts sensor data in one of the following formats:
 * - **SenML JSON** (RFC 8428): `Content-Type: application/json`
 * - **CSV**: `Content-Type: text/csv` or `application/csv`
 * - **Apache Arrow IPC**: `Content-Type: application/vnd.apache.arrow.file`
 *
 * If no Content-Type header is provided, defaults to CSV format.
 */
export const publishSensorsDataMutation = (options?: Partial<Options<PublishSensorsDataData>>): UseMutationOptions<PublishSensorsDataResponse, PublishSensorsDataError, Options<PublishSensorsDataData>> => {
    const mutationOptions: UseMutationOptions<PublishSensorsDataResponse, PublishSensorsDataError, Options<PublishSensorsDataData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await publishSensorsData({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listSeriesQueryKey = (options?: Options<ListSeriesData>) => createQueryKey('listSeries', options);

/**
 * List all series (time series) in DCAT catalog format.
 */
export const listSeriesOptions = (options?: Options<ListSeriesData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof listSeriesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listSeries({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listSeriesQueryKey(options)
});

export const getSeriesDataQueryKey = (options: Options<GetSeriesDataData>) => createQueryKey('getSeriesData', options);

/**
 * Get series data in various formats based on query parameter.
 */
export const getSeriesDataOptions = (options: Options<GetSeriesDataData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getSeriesDataQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSeriesData({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSeriesDataQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getSeriesDataInfiniteQueryKey = (options: Options<GetSeriesDataData>): QueryKey<Options<GetSeriesDataData>> => createQueryKey('getSeriesData', options, true);

/**
 * Get series data in various formats based on query parameter.
 */
export const getSeriesDataInfiniteOptions = (options: Options<GetSeriesDataData>) => infiniteQueryOptions<unknown, DefaultError, InfiniteData<unknown>, QueryKey<Options<GetSeriesDataData>>, string | Pick<QueryKey<Options<GetSeriesDataData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetSeriesDataData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                start: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getSeriesData({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSeriesDataInfiniteQueryKey(options)
});
