// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { FrontpageData, FrontpageResponses, GetSeriesDataData, GetSeriesDataErrors, GetSeriesDataResponses, ListMetricsData, ListMetricsResponses, ListSeriesData, ListSeriesResponses, LivenessData, LivenessResponses, PrometheusMetricsData, PrometheusMetricsResponses, PrometheusRemoteReadData, PrometheusRemoteReadErrors, PrometheusRemoteReadResponses, PublishInfluxdbData, PublishInfluxdbErrors, PublishInfluxdbResponses, PublishPrometheusData, PublishPrometheusErrors, PublishPrometheusResponses, PublishSensorsDataData, PublishSensorsDataErrors, PublishSensorsDataResponses, ReadinessData, ReadinessErrors, ReadinessResponses, SimplePromqlQueryData, SimplePromqlQueryErrors, SimplePromqlQueryResponses, VacuumDatabaseData, VacuumDatabaseErrors, VacuumDatabaseResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const frontpage = <ThrowOnError extends boolean = false>(options?: Options<FrontpageData, ThrowOnError>) => (options?.client ?? client).get<FrontpageResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Database Vacuuming
 *
 * Cleans up and optimizes the database by removing unused data and reclaiming space.
 * (only if supported by the underlying storage engine).
 */
export const vacuumDatabase = <ThrowOnError extends boolean = false>(options?: Options<VacuumDatabaseData, ThrowOnError>) => (options?.client ?? client).post<VacuumDatabaseResponses, VacuumDatabaseErrors, ThrowOnError>({ url: '/api/v1/admin/vacuum', ...options });

/**
 * Prometheus Remote Read API.
 *
 * Allows you to read data from SensApp using Prometheus remote read protocol.
 *
 * It follows the [Prometheus Remote Read specification](https://prometheus.io/docs/prometheus/latest/querying/remote_read_api/).
 */
export const prometheusRemoteRead = <ThrowOnError extends boolean = false>(options: Options<PrometheusRemoteReadData, ThrowOnError>) => (options.client ?? client).post<PrometheusRemoteReadResponses, PrometheusRemoteReadErrors, ThrowOnError>({ url: '/api/v1/prometheus_remote_read', ...options });

/**
 * Prometheus Remote Write API.
 *
 * Allows you to write data from Prometheus to SensApp.
 *
 * It follows the [Prometheus Remote Write specification](https://prometheus.io/docs/concepts/remote_write_spec/).
 */
export const publishPrometheus = <ThrowOnError extends boolean = false>(options: Options<PublishPrometheusData, ThrowOnError>) => (options.client ?? client).post<PublishPrometheusResponses, PublishPrometheusErrors, ThrowOnError>({ url: '/api/v1/prometheus_remote_write', ...options });

/**
 * Simple PromQL query endpoint.
 *
 * Parses a PromQL expression and returns matching time series data.
 * Only simple selectors (VectorSelector and MatrixSelector) are supported.
 *
 * # Examples
 *
 * - Simple metric: `GET /api/v1/query?query=my_metric`
 * - With labels: `GET /api/v1/query?query=my_metric{env="prod"}`
 * - Range query: `GET /api/v1/query?query=my_metric[5m]`
 * - With format: `GET /api/v1/query?query=my_metric&format=csv`
 */
export const simplePromqlQuery = <ThrowOnError extends boolean = false>(options: Options<SimplePromqlQueryData, ThrowOnError>) => (options.client ?? client).get<SimplePromqlQueryResponses, SimplePromqlQueryErrors, ThrowOnError>({ url: '/api/v1/query', ...options });

/**
 * InfluxDB Compatible Write API.
 *
 * Allows you to write data from InfluxDB or Telegraf to SensApp.
 * [More information.](https://github.com/SINTEF/sensapp/blob/main/docs/INFLUX_DB.md)
 */
export const publishInfluxdb = <ThrowOnError extends boolean = false>(options: Options<PublishInfluxdbData, ThrowOnError>) => (options.client ?? client).post<PublishInfluxdbResponses, PublishInfluxdbErrors, ThrowOnError>({
    bodySerializer: null,
    url: '/api/v2/write',
    ...options,
    headers: {
        'Content-Type': 'text/plain',
        ...options.headers
    }
});

/**
 * Liveness check
 *
 * Checks if the service is running.
 * This endpoint always returns 200 OK if the server is able to respond.
 */
export const liveness = <ThrowOnError extends boolean = false>(options?: Options<LivenessData, ThrowOnError>) => (options?.client ?? client).get<LivenessResponses, unknown, ThrowOnError>({ url: '/health/live', ...options });

/**
 * Readiness check
 *
 * Checks if the service is ready to accept traffic.
 * This includes checking if the database connection is working
 */
export const readiness = <ThrowOnError extends boolean = false>(options?: Options<ReadinessData, ThrowOnError>) => (options?.client ?? client).get<ReadinessResponses, ReadinessErrors, ThrowOnError>({ url: '/health/ready', ...options });

/**
 * List unique metrics (measurement types) with aggregated information in DCAT catalog format.
 */
export const listMetrics = <ThrowOnError extends boolean = false>(options?: Options<ListMetricsData, ThrowOnError>) => (options?.client ?? client).get<ListMetricsResponses, unknown, ThrowOnError>({ url: '/metrics', ...options });

export const prometheusMetrics = <ThrowOnError extends boolean = false>(options?: Options<PrometheusMetricsData, ThrowOnError>) => (options?.client ?? client).get<PrometheusMetricsResponses, unknown, ThrowOnError>({ url: '/prometheus/metrics', ...options });

/**
 * SensApp native data ingestion API supporting multiple formats.
 *
 * Accepts sensor data in one of the following formats:
 * - **SenML JSON** (RFC 8428): `Content-Type: application/json`
 * - **CSV**: `Content-Type: text/csv` or `application/csv`
 * - **Apache Arrow IPC**: `Content-Type: application/vnd.apache.arrow.file`
 *
 * If no Content-Type header is provided, defaults to CSV format.
 */
export const publishSensorsData = <ThrowOnError extends boolean = false>(options: Options<PublishSensorsDataData, ThrowOnError>) => (options.client ?? client).post<PublishSensorsDataResponses, PublishSensorsDataErrors, ThrowOnError>({
    bodySerializer: null,
    url: '/publish',
    ...options,
    headers: {
        'Content-Type': 'text/plain',
        ...options.headers
    }
});

/**
 * List all series (time series) in DCAT catalog format.
 */
export const listSeries = <ThrowOnError extends boolean = false>(options?: Options<ListSeriesData, ThrowOnError>) => (options?.client ?? client).get<ListSeriesResponses, unknown, ThrowOnError>({ url: '/series', ...options });

/**
 * Get series data in various formats based on query parameter.
 */
export const getSeriesData = <ThrowOnError extends boolean = false>(options: Options<GetSeriesDataData, ThrowOnError>) => (options.client ?? client).get<GetSeriesDataResponses, GetSeriesDataErrors, ThrowOnError>({ url: '/series/{series_uuid}', ...options });
