// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AppError = {
    InternalServerError: string;
} | {
    BadRequest: string;
} | {
    NotFound: string;
} | {
    Unauthorized: string;
} | {
    Forbidden: string;
} | {
    Storage: string;
};

export type HealthResponse = {
    status: string;
};

export type ReadinessResponse = {
    database: string;
    error?: string | null;
    status: string;
};

/**
 * What a vacuum did.
 */
export type VacuumResponse = {
    /**
     * Number of duplicate samples removed (same series, same timestamp, same value, the first
     * one written is kept), or `null` when the storage backend cannot remove duplicates
     */
    duplicates_removed?: number | null;
    /**
     * `ok` when the maintenance completed
     */
    status: string;
};

export type FrontpageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type FrontpageResponses = {
    /**
     * SensApp Frontpage: the name of the instance. Redirects to the web UI at `/ui/` instead when the UI is served
     */
    200: string;
};

export type FrontpageResponse = FrontpageResponses[keyof FrontpageResponses];

export type VacuumDatabaseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/vacuum';
};

export type VacuumDatabaseErrors = {
    /**
     * The token does not have the delete scope, or has a sensor allow list
     */
    403: unknown;
    /**
     * Failed to vacuum database
     */
    500: string;
    /**
     * The storage backend is unavailable: retry later
     */
    503: unknown;
    /**
     * The request took longer than SENSAPP_HTTP_MAINTENANCE_TIMEOUT_SECONDS (one hour by default), and the storage backend may carry on after the answer
     */
    504: unknown;
};

export type VacuumDatabaseError = VacuumDatabaseErrors[keyof VacuumDatabaseErrors];

export type VacuumDatabaseResponses = {
    /**
     * Maintenance completed, with the number of duplicate samples removed
     */
    200: VacuumResponse;
};

export type VacuumDatabaseResponse = VacuumDatabaseResponses[keyof VacuumDatabaseResponses];

export type PrometheusRemoteReadData = {
    /**
     * Prometheus Remote Read endpoint. [Reference](https://prometheus.io/docs/prometheus/latest/querying/remote_read_api/)
     */
    body?: unknown;
    headers: {
        /**
         * Content encoding, must be snappy
         */
        'content-encoding': string;
        /**
         * Content type, must be application/x-protobuf
         */
        'content-type': string;
        /**
         * Prometheus Remote Read version, must be 0.1.0
         */
        'x-prometheus-remote-read-version': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/prometheus_remote_read';
};

export type PrometheusRemoteReadErrors = {
    /**
     * Bad Request
     */
    400: AppError;
    /**
     * Internal Server Error
     */
    500: AppError;
    /**
     * The storage backend is unavailable: retry later
     */
    503: unknown;
    /**
     * The request took longer than SENSAPP_HTTP_SERVER_TIMEOUT_SECONDS, usually because the storage backend hangs
     */
    504: unknown;
};

export type PrometheusRemoteReadError = PrometheusRemoteReadErrors[keyof PrometheusRemoteReadErrors];

export type PrometheusRemoteReadResponses = {
    /**
     * Read Response
     */
    200: unknown;
};

export type PublishPrometheusData = {
    /**
     * Prometheus Remote Write endpoint. [Reference](https://prometheus.io/docs/concepts/remote_write_spec/)
     */
    body?: unknown;
    headers: {
        /**
         * Content encoding, must be snappy
         */
        'content-encoding': string;
        /**
         * Content type, must be application/x-protobuf
         */
        'content-type': string;
        /**
         * Prometheus Remote Write version, must be 0.1.0
         */
        'x-prometheus-remote-write-version': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/prometheus_remote_write';
};

export type PublishPrometheusErrors = {
    /**
     * Bad Request
     */
    400: AppError;
    /**
     * Internal Server Error
     */
    500: AppError;
    /**
     * The storage backend is unavailable, or SensApp is busy writing and sheds the write. A `Retry-After` header (seconds, randomised) means the request was not processed at all and can be sent again after that delay
     */
    503: unknown;
    /**
     * The request took longer than SENSAPP_HTTP_SERVER_TIMEOUT_SECONDS, usually because the storage backend hangs
     */
    504: unknown;
};

export type PublishPrometheusError = PublishPrometheusErrors[keyof PublishPrometheusErrors];

export type PublishPrometheusResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PublishPrometheusResponse = PublishPrometheusResponses[keyof PublishPrometheusResponses];

export type SimplePromqlQueryData = {
    body?: never;
    path?: never;
    query: {
        /**
         * PromQL query string (e.g., 'my_metric{label="value"}' or 'my_metric[5m]')
         */
        query: string;
        /**
         * Output format: senml (default), csv, jsonl, or arrow
         */
        format?: string;
        /**
         * Bucket width for aggregation queries, using Prometheus duration syntax (e.g., '5m'). Without it, the whole window is one bucket
         */
        step?: string;
    };
    url: '/api/v1/query';
};

export type SimplePromqlQueryErrors = {
    /**
     * Invalid or unsupported PromQL query
     */
    400: unknown;
    /**
     * Internal server error
     */
    500: unknown;
    /**
     * The storage backend is unavailable: retry later
     */
    503: unknown;
    /**
     * The request took longer than SENSAPP_HTTP_SERVER_TIMEOUT_SECONDS, usually because the storage backend hangs
     */
    504: unknown;
};

export type SimplePromqlQueryResponses = {
    /**
     * Query results in requested format
     */
    200: unknown;
};

export type PublishInfluxdbData = {
    /**
     * InfluxDB Line Protocol endpoint. [Reference](https://docs.influxdata.com/influxdb/v2/reference/syntax/line-protocol/).
     */
    body: string;
    path?: never;
    query: {
        /**
         * Bucket name
         */
        bucket: string;
        /**
         * Organization name
         */
        org?: string;
        /**
         * Organization ID
         */
        org_id?: string;
        /**
         * Precision of the timestamps. One of ns, us, ms, s
         */
        precision?: string;
    };
    url: '/api/v2/write';
};

export type PublishInfluxdbErrors = {
    /**
     * Bad Request
     */
    400: AppError;
    /**
     * Internal Server Error
     */
    500: AppError;
    /**
     * The storage backend is unavailable, or SensApp is busy writing and sheds the write. A `Retry-After` header (seconds, randomised) means the request was not processed at all and can be sent again after that delay
     */
    503: unknown;
    /**
     * The request took longer than SENSAPP_HTTP_SERVER_TIMEOUT_SECONDS, usually because the storage backend hangs
     */
    504: unknown;
};

export type PublishInfluxdbError = PublishInfluxdbErrors[keyof PublishInfluxdbErrors];

export type PublishInfluxdbResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PublishInfluxdbResponse = PublishInfluxdbResponses[keyof PublishInfluxdbResponses];

export type LivenessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/live';
};

export type LivenessResponses = {
    /**
     * Service is alive
     */
    200: HealthResponse;
};

export type LivenessResponse = LivenessResponses[keyof LivenessResponses];

export type ReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type ReadinessErrors = {
    /**
     * Service is not ready
     */
    503: ReadinessResponse;
};

export type ReadinessError = ReadinessErrors[keyof ReadinessErrors];

export type ReadinessResponses = {
    /**
     * Service is ready
     */
    200: ReadinessResponse;
};

export type ReadinessResponse2 = ReadinessResponses[keyof ReadinessResponses];

export type ListMetricsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter metrics by name (substring match)
         */
        name?: string;
        /**
         * Filter metrics by name using regex pattern
         */
        name_regex?: string;
        /**
         * Filter metrics by sensor type (float, integer, string, boolean, location, json, blob, numeric)
         */
        type?: string;
    };
    url: '/metrics';
};

export type ListMetricsErrors = {
    /**
     * The storage backend is unavailable: retry later
     */
    503: unknown;
    /**
     * The request took longer than SENSAPP_HTTP_SERVER_TIMEOUT_SECONDS, usually because the storage backend hangs
     */
    504: unknown;
};

export type ListMetricsResponses = {
    /**
     * Metrics catalog in DCAT format
     */
    200: unknown;
};

export type PrometheusMetricsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Append the most recent sample for Prometheus-compatible series
         */
        include_latest_samples?: boolean;
        /**
         * Optional metric name filter used when include_latest_samples=true
         */
        metric?: string;
        /**
         * Optional PromQL-style label selector used when include_latest_samples=true
         */
        selector?: string;
    };
    url: '/prometheus/metrics';
};

export type PrometheusMetricsResponses = {
    /**
     * Prometheus-compatible metrics
     */
    200: string;
};

export type PrometheusMetricsResponse = PrometheusMetricsResponses[keyof PrometheusMetricsResponses];

export type PublishSensorsDataData = {
    /**
     * Sensor data in SenML JSON, CSV, or Apache Arrow format
     */
    body: string;
    path?: never;
    query?: never;
    url: '/publish';
};

export type PublishSensorsDataErrors = {
    /**
     * Bad Request - invalid data format
     */
    400: AppError;
    /**
     * Internal Server Error
     */
    500: AppError;
    /**
     * The storage backend is unavailable, or SensApp is busy writing and sheds the write. A `Retry-After` header (seconds, randomised) means the request was not processed at all and can be sent again after that delay
     */
    503: unknown;
    /**
     * The request took longer than SENSAPP_HTTP_SERVER_TIMEOUT_SECONDS, usually because the storage backend hangs
     */
    504: unknown;
};

export type PublishSensorsDataError = PublishSensorsDataErrors[keyof PublishSensorsDataErrors];

export type PublishSensorsDataResponses = {
    /**
     * Data ingested successfully
     */
    200: string;
};

export type PublishSensorsDataResponse = PublishSensorsDataResponses[keyof PublishSensorsDataResponses];

export type ListSeriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter series by metric name
         */
        metric?: string;
        /**
         * PromQL-style label selector (e.g., '{env="prod",region=~"us.*"}')
         */
        selector?: string;
        /**
         * Series per page, 256 by default, 16384 at most
         */
        limit?: number;
        /**
         * Cursor of the next page: the `bookmark` of the `hydra:next` link of the previous page
         */
        bookmark?: string;
    };
    url: '/series';
};

export type ListSeriesErrors = {
    /**
     * The storage backend is unavailable: retry later
     */
    503: unknown;
    /**
     * The request took longer than SENSAPP_HTTP_SERVER_TIMEOUT_SECONDS, usually because the storage backend hangs
     */
    504: unknown;
};

export type ListSeriesResponses = {
    /**
     * Time series catalog in DCAT format. A full page has a `hydra:view` with the link to the next page
     */
    200: unknown;
};

export type DeleteSeriesData = {
    body?: never;
    path: {
        /**
         * UUID of the series to delete
         */
        series_uuid: string;
    };
    query?: never;
    url: '/series/{series_uuid}';
};

export type DeleteSeriesErrors = {
    /**
     * Invalid UUID
     */
    400: unknown;
    /**
     * The token does not have the delete scope
     */
    403: unknown;
    /**
     * Series not found
     */
    404: unknown;
    /**
     * The storage backend does not support deletion
     */
    501: unknown;
    /**
     * The storage backend is unavailable: retry later
     */
    503: unknown;
    /**
     * The request took longer than SENSAPP_HTTP_SERVER_TIMEOUT_SECONDS, usually because the storage backend hangs
     */
    504: unknown;
};

export type DeleteSeriesResponses = {
    /**
     * Series deleted
     */
    204: void;
};

export type DeleteSeriesResponse = DeleteSeriesResponses[keyof DeleteSeriesResponses];

export type GetSeriesDataData = {
    body?: never;
    path: {
        /**
         * UUID of the series
         */
        series_uuid: string;
    };
    query?: {
        /**
         * Output format: senml, csv, or jsonl (default: senml)
         */
        format?: string;
        /**
         * Start datetime in ISO 8601 format (e.g., '2024-01-15T10:30:00Z')
         */
        start?: string;
        /**
         * End datetime in ISO 8601 format (e.g., '2024-01-15T11:00:00Z')
         */
        end?: string;
        /**
         * Maximum number of samples (at most 100,000). Returns the oldest N samples of the window, in time order, and silently drops the rest. With simplify, it bounds the rows read before simplification
         */
        limit?: number;
        /**
         * Bucket width using Prometheus duration syntax (e.g., '1h', '5m', '1d')
         */
        step?: string;
        /**
         * Aggregation function: avg, min, max, sum, count, first, last
         */
        aggregation?: string;
        /**
         * Explicitly enable simplify-based point reduction. Applied to the rows read for the window (after bucketing when step is set); more than 100,000 rows to simplify is rejected with HTTP 400 instead of being truncated, so use step/aggregation or a narrower start/end
         */
        simplify?: boolean;
        /**
         * Dimensionless simplify tolerance on normalized time/value coordinates
         */
        simplify_tolerance?: number;
        /**
         * Use Douglas-Peucker only when simplifying
         */
        simplify_high_quality?: boolean;
    };
    url: '/series/{series_uuid}';
};

export type GetSeriesDataErrors = {
    /**
     * Invalid format
     */
    400: unknown;
    /**
     * Series not found
     */
    404: unknown;
    /**
     * The storage backend is unavailable: retry later
     */
    503: unknown;
    /**
     * The request took longer than SENSAPP_HTTP_SERVER_TIMEOUT_SECONDS, usually because the storage backend hangs
     */
    504: unknown;
};

export type GetSeriesDataResponses = {
    /**
     * Series data in requested format
     */
    200: unknown;
};

export type GetSeriesAvailabilityData = {
    body?: never;
    path: {
        /**
         * UUID of the series
         */
        series_uuid: string;
    };
    query: {
        /**
         * Inclusive start datetime in ISO 8601 format
         */
        start: string;
        /**
         * Inclusive end datetime in ISO 8601 format
         */
        end: string;
        /**
         * Optional bucket width using Prometheus duration syntax for coverage calculation
         */
        step?: string;
    };
    url: '/series/{series_uuid}/availability';
};

export type GetSeriesAvailabilityErrors = {
    /**
     * Invalid query parameters
     */
    400: unknown;
    /**
     * Series not found
     */
    404: unknown;
    /**
     * The storage backend is unavailable: retry later
     */
    503: unknown;
    /**
     * The request took longer than SENSAPP_HTTP_SERVER_TIMEOUT_SECONDS, usually because the storage backend hangs
     */
    504: unknown;
};

export type GetSeriesAvailabilityResponses = {
    /**
     * Availability information for the requested series and window
     */
    200: unknown;
};

export type GetSeriesLastSampleData = {
    body?: never;
    path: {
        /**
         * UUID of the series
         */
        series_uuid: string;
    };
    query?: {
        /**
         * Optional inclusive start datetime in ISO 8601 format
         */
        start?: string;
        /**
         * Optional inclusive end datetime in ISO 8601 format
         */
        end?: string;
    };
    url: '/series/{series_uuid}/last';
};

export type GetSeriesLastSampleErrors = {
    /**
     * Invalid query parameters
     */
    400: unknown;
    /**
     * Series not found or no sample matched the requested window
     */
    404: unknown;
    /**
     * The storage backend is unavailable: retry later
     */
    503: unknown;
    /**
     * The request took longer than SENSAPP_HTTP_SERVER_TIMEOUT_SECONDS, usually because the storage backend hangs
     */
    504: unknown;
};

export type GetSeriesLastSampleResponses = {
    /**
     * Latest sample for the requested series
     */
    200: unknown;
};

export type DeleteSeriesSamplesData = {
    body?: never;
    path: {
        /**
         * UUID of the series
         */
        series_uuid: string;
    };
    query: {
        /**
         * Inclusive start datetime in ISO 8601 format
         */
        start: string;
        /**
         * Inclusive end datetime in ISO 8601 format
         */
        end: string;
    };
    url: '/series/{series_uuid}/samples';
};

export type DeleteSeriesSamplesErrors = {
    /**
     * Invalid UUID, or missing or invalid time bounds
     */
    400: unknown;
    /**
     * The token does not have the delete scope
     */
    403: unknown;
    /**
     * Series not found
     */
    404: unknown;
    /**
     * The storage backend does not support deletion
     */
    501: unknown;
    /**
     * The storage backend is unavailable: retry later
     */
    503: unknown;
    /**
     * The request took longer than SENSAPP_HTTP_SERVER_TIMEOUT_SECONDS, usually because the storage backend hangs
     */
    504: unknown;
};

export type DeleteSeriesSamplesResponses = {
    /**
     * Number of deleted samples
     */
    200: unknown;
};
