// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AppError = {
    InternalServerError: string;
} | {
    BadRequest: string;
} | {
    NotFound: string;
} | {
    Unauthorized: string;
} | {
    Forbidden: string;
} | {
    Storage: string;
};

export type HealthResponse = {
    status: string;
};

export type ReadinessResponse = {
    database: string;
    error?: string | null;
    status: string;
};

export type FrontpageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type FrontpageResponses = {
    /**
     * SensApp Frontpage
     */
    200: string;
};

export type FrontpageResponse = FrontpageResponses[keyof FrontpageResponses];

export type VacuumDatabaseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/vacuum';
};

export type VacuumDatabaseErrors = {
    /**
     * Failed to vacuum database
     */
    500: string;
};

export type VacuumDatabaseError = VacuumDatabaseErrors[keyof VacuumDatabaseErrors];

export type VacuumDatabaseResponses = {
    /**
     * Database vacuum completed successfully
     */
    200: string;
};

export type VacuumDatabaseResponse = VacuumDatabaseResponses[keyof VacuumDatabaseResponses];

export type PrometheusRemoteReadData = {
    /**
     * Prometheus Remote Read endpoint. [Reference](https://prometheus.io/docs/prometheus/latest/querying/remote_read_api/)
     */
    body?: unknown;
    headers: {
        /**
         * Content encoding, must be snappy
         */
        'content-encoding': string;
        /**
         * Content type, must be application/x-protobuf
         */
        'content-type': string;
        /**
         * Prometheus Remote Read version, must be 0.1.0
         */
        'x-prometheus-remote-read-version': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/prometheus_remote_read';
};

export type PrometheusRemoteReadErrors = {
    /**
     * Bad Request
     */
    400: AppError;
    /**
     * Internal Server Error
     */
    500: AppError;
};

export type PrometheusRemoteReadError = PrometheusRemoteReadErrors[keyof PrometheusRemoteReadErrors];

export type PrometheusRemoteReadResponses = {
    /**
     * Read Response
     */
    200: unknown;
};

export type PublishPrometheusData = {
    /**
     * Prometheus Remote Write endpoint. [Reference](https://prometheus.io/docs/concepts/remote_write_spec/)
     */
    body?: unknown;
    headers: {
        /**
         * Content encoding, must be snappy
         */
        'content-encoding': string;
        /**
         * Content type, must be application/x-protobuf
         */
        'content-type': string;
        /**
         * Prometheus Remote Write version, must be 0.1.0
         */
        'x-prometheus-remote-write-version': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/prometheus_remote_write';
};

export type PublishPrometheusErrors = {
    /**
     * Bad Request
     */
    400: AppError;
    /**
     * Internal Server Error
     */
    500: AppError;
};

export type PublishPrometheusError = PublishPrometheusErrors[keyof PublishPrometheusErrors];

export type PublishPrometheusResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PublishPrometheusResponse = PublishPrometheusResponses[keyof PublishPrometheusResponses];

export type SimplePromqlQueryData = {
    body?: never;
    path?: never;
    query: {
        /**
         * PromQL query string (e.g., 'my_metric{label="value"}' or 'my_metric[5m]')
         */
        query: string;
        /**
         * Output format: senml (default), csv, jsonl, or arrow
         */
        format?: string;
    };
    url: '/api/v1/query';
};

export type SimplePromqlQueryErrors = {
    /**
     * Invalid or unsupported PromQL query
     */
    400: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type SimplePromqlQueryResponses = {
    /**
     * Query results in requested format
     */
    200: unknown;
};

export type PublishInfluxdbData = {
    /**
     * InfluxDB Line Protocol endpoint. [Reference](https://docs.influxdata.com/influxdb/v2/reference/syntax/line-protocol/).
     */
    body: string;
    path?: never;
    query: {
        /**
         * Bucket name
         */
        bucket: string;
        /**
         * Organization name
         */
        org?: string;
        /**
         * Organization ID
         */
        org_id?: string;
        /**
         * Precision of the timestamps. One of ns, us, ms, s
         */
        precision?: string;
    };
    url: '/api/v2/write';
};

export type PublishInfluxdbErrors = {
    /**
     * Bad Request
     */
    400: AppError;
    /**
     * Internal Server Error
     */
    500: AppError;
};

export type PublishInfluxdbError = PublishInfluxdbErrors[keyof PublishInfluxdbErrors];

export type PublishInfluxdbResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PublishInfluxdbResponse = PublishInfluxdbResponses[keyof PublishInfluxdbResponses];

export type LivenessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/live';
};

export type LivenessResponses = {
    /**
     * Service is alive
     */
    200: HealthResponse;
};

export type LivenessResponse = LivenessResponses[keyof LivenessResponses];

export type ReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type ReadinessErrors = {
    /**
     * Service is not ready
     */
    503: ReadinessResponse;
};

export type ReadinessError = ReadinessErrors[keyof ReadinessErrors];

export type ReadinessResponses = {
    /**
     * Service is ready
     */
    200: ReadinessResponse;
};

export type ReadinessResponse2 = ReadinessResponses[keyof ReadinessResponses];

export type ListMetricsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter metrics by name (substring match)
         */
        name?: string;
        /**
         * Filter metrics by name using regex pattern
         */
        name_regex?: string;
        /**
         * Filter metrics by sensor type (float, integer, string, boolean, location, json, blob, numeric)
         */
        type?: string;
    };
    url: '/metrics';
};

export type ListMetricsResponses = {
    /**
     * Metrics catalog in DCAT format
     */
    200: unknown;
};

export type PrometheusMetricsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/prometheus/metrics';
};

export type PrometheusMetricsResponses = {
    /**
     * Prometheus-compatible metrics
     */
    200: string;
};

export type PrometheusMetricsResponse = PrometheusMetricsResponses[keyof PrometheusMetricsResponses];

export type PublishSensorsDataData = {
    /**
     * Sensor data in SenML JSON, CSV, or Apache Arrow format
     */
    body: string;
    path?: never;
    query?: never;
    url: '/publish';
};

export type PublishSensorsDataErrors = {
    /**
     * Bad Request - invalid data format
     */
    400: AppError;
    /**
     * Internal Server Error
     */
    500: AppError;
};

export type PublishSensorsDataError = PublishSensorsDataErrors[keyof PublishSensorsDataErrors];

export type PublishSensorsDataResponses = {
    /**
     * Data ingested successfully
     */
    200: string;
};

export type PublishSensorsDataResponse = PublishSensorsDataResponses[keyof PublishSensorsDataResponses];

export type ListSeriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter series by metric name
         */
        metric?: string;
        /**
         * PromQL-style label selector (e.g., '{env="prod",region=~"us.*"}')
         */
        selector?: string;
    };
    url: '/series';
};

export type ListSeriesResponses = {
    /**
     * Time series catalog in DCAT format
     */
    200: unknown;
};

export type GetSeriesDataData = {
    body?: never;
    path: {
        /**
         * UUID of the series
         */
        series_uuid: string;
    };
    query?: {
        /**
         * Output format: senml, csv, or jsonl (default: senml)
         */
        format?: string;
        /**
         * Start datetime in ISO 8601 format (e.g., '2024-01-15T10:30:00Z')
         */
        start?: string;
        /**
         * End datetime in ISO 8601 format (e.g., '2024-01-15T11:00:00Z')
         */
        end?: string;
        /**
         * Maximum number of samples (default: 10,000,000)
         */
        limit?: number;
    };
    url: '/series/{series_uuid}';
};

export type GetSeriesDataErrors = {
    /**
     * Invalid format
     */
    400: unknown;
    /**
     * Series not found
     */
    404: unknown;
};

export type GetSeriesDataResponses = {
    /**
     * Series data in requested format
     */
    200: unknown;
};
