apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sensapp.fullname" . }}
  labels:
    {{- include "sensapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  SENSAPP_STORAGE_CONNECTION_STRING: {{ .Values.storage.connectionString | quote }}
  {{- if .Values.auth.jwtSecret }}
  SENSAPP_JWT_SECRET: {{ .Values.auth.jwtSecret | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
