name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          #- nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup component add clippy
      - run: cargo install sqlx-cli --no-default-features --features sqlite
      - run: touch test.db && cargo sqlx migrate run --source src/storage/sqlite/migrations --database-url sqlite://test.db && cargo sqlx prepare --database-url sqlite://test.db
      - run: cargo clippy --verbose
      - run: cargo build --verbose
      - run: cargo test --verbose
