name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  # PostgreSQL test settings
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres
  POSTGRES_DB: sensapp
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/sensapp
  TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432

jobs:
  build_and_test:
    name: Rust project with PostgreSQL
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: sensapp
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install stable --profile minimal --component clippy llvm-tools-preview --no-self-update
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"

      # Install sqlx-cli for PostgreSQL
      - run: cargo install sqlx-cli --no-default-features --features postgres

      # Run PostgreSQL migrations and prepare
      - run: cargo sqlx migrate run --source src/storage/postgresql/migrations --database-url $DATABASE_URL
      - run: cargo sqlx prepare --database-url $DATABASE_URL

      # Run linting
      - run: cargo clippy --verbose

      # Run tests with coverage
      - run: cargo llvm-cov --verbose --lcov --output-path lcov.info

      # Run integration tests
      - run: cargo test --test ingestion --verbose
        env:
          TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432

      # Upload coverage
      - uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: lcov.info
          min_coverage: 50
